// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: acme/v1/acme.proto

package acmev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Something int32

const (
	Something_SOMETHING_UNSPECIFIED Something = 0
	Something_SOMETHING_ONE         Something = 1
	Something_SOMETHING_TWO         Something = 2
)

// Enum value maps for Something.
var (
	Something_name = map[int32]string{
		0: "SOMETHING_UNSPECIFIED",
		1: "SOMETHING_ONE",
		2: "SOMETHING_TWO",
	}
	Something_value = map[string]int32{
		"SOMETHING_UNSPECIFIED": 0,
		"SOMETHING_ONE":         1,
		"SOMETHING_TWO":         2,
	}
)

func (x Something) Enum() *Something {
	p := new(Something)
	*p = x
	return p
}

func (x Something) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Something) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_acme_proto_enumTypes[0].Descriptor()
}

func (Something) Type() protoreflect.EnumType {
	return &file_acme_v1_acme_proto_enumTypes[0]
}

func (x Something) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Example struct {
	state                    protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Name          *string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Age           int32                   `protobuf:"varint,2,opt,name=age"`
	xxx_hidden_Hobbies       []string                `protobuf:"bytes,3,rep,name=hobbies"`
	xxx_hidden_Metadata      map[string]string       `protobuf:"bytes,4,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_OptionalField isExample_OptionalField `protobuf_oneof:"optional_field"`
	xxx_hidden_NestedExample *[]*Example             `protobuf:"bytes,7,rep,name=nested_example,json=nestedExample"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_acme_v1_acme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_acme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Example) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Example) GetAge() int32 {
	if x != nil {
		return x.xxx_hidden_Age
	}
	return 0
}

func (x *Example) GetHobbies() []string {
	if x != nil {
		return x.xxx_hidden_Hobbies
	}
	return nil
}

func (x *Example) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Example) GetEmail() string {
	if x != nil {
		if x, ok := x.xxx_hidden_OptionalField.(*example_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Example) GetPhoneNumber() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_OptionalField.(*example_PhoneNumber); ok {
			return x.PhoneNumber
		}
	}
	return 0
}

func (x *Example) GetNestedExample() []*Example {
	if x != nil {
		if x.xxx_hidden_NestedExample != nil {
			return *x.xxx_hidden_NestedExample
		}
	}
	return nil
}

func (x *Example) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Example) SetAge(v int32) {
	x.xxx_hidden_Age = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Example) SetHobbies(v []string) {
	x.xxx_hidden_Hobbies = v
}

func (x *Example) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Example) SetEmail(v string) {
	x.xxx_hidden_OptionalField = &example_Email{v}
}

func (x *Example) SetPhoneNumber(v int32) {
	x.xxx_hidden_OptionalField = &example_PhoneNumber{v}
}

func (x *Example) SetNestedExample(v []*Example) {
	x.xxx_hidden_NestedExample = &v
}

func (x *Example) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Example) HasAge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Example) HasOptionalField() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OptionalField != nil
}

func (x *Example) HasEmail() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_OptionalField.(*example_Email)
	return ok
}

func (x *Example) HasPhoneNumber() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_OptionalField.(*example_PhoneNumber)
	return ok
}

func (x *Example) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Example) ClearAge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Age = 0
}

func (x *Example) ClearOptionalField() {
	x.xxx_hidden_OptionalField = nil
}

func (x *Example) ClearEmail() {
	if _, ok := x.xxx_hidden_OptionalField.(*example_Email); ok {
		x.xxx_hidden_OptionalField = nil
	}
}

func (x *Example) ClearPhoneNumber() {
	if _, ok := x.xxx_hidden_OptionalField.(*example_PhoneNumber); ok {
		x.xxx_hidden_OptionalField = nil
	}
}

const Example_OptionalField_not_set_case case_Example_OptionalField = 0
const Example_Email_case case_Example_OptionalField = 5
const Example_PhoneNumber_case case_Example_OptionalField = 6

func (x *Example) WhichOptionalField() case_Example_OptionalField {
	if x == nil {
		return Example_OptionalField_not_set_case
	}
	switch x.xxx_hidden_OptionalField.(type) {
	case *example_Email:
		return Example_Email_case
	case *example_PhoneNumber:
		return Example_PhoneNumber_case
	default:
		return Example_OptionalField_not_set_case
	}
}

type Example_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name     *string
	Age      *int32
	Hobbies  []string
	Metadata map[string]string
	// Fields of oneof xxx_hidden_OptionalField:
	Email       *string
	PhoneNumber *int32
	// -- end of xxx_hidden_OptionalField
	NestedExample []*Example
}

func (b0 Example_builder) Build() *Example {
	m0 := &Example{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Age != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Age = *b.Age
	}
	x.xxx_hidden_Hobbies = b.Hobbies
	x.xxx_hidden_Metadata = b.Metadata
	if b.Email != nil {
		x.xxx_hidden_OptionalField = &example_Email{*b.Email}
	}
	if b.PhoneNumber != nil {
		x.xxx_hidden_OptionalField = &example_PhoneNumber{*b.PhoneNumber}
	}
	x.xxx_hidden_NestedExample = &b.NestedExample
	return m0
}

type case_Example_OptionalField protoreflect.FieldNumber

func (x case_Example_OptionalField) String() string {
	md := file_acme_v1_acme_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExample_OptionalField interface {
	isExample_OptionalField()
}

type example_Email struct {
	Email string `protobuf:"bytes,5,opt,name=email,oneof"`
}

type example_PhoneNumber struct {
	PhoneNumber int32 `protobuf:"varint,6,opt,name=phone_number,json=phoneNumber,oneof"`
}

func (*example_Email) isExample_OptionalField() {}

func (*example_PhoneNumber) isExample_OptionalField() {}

type SomethingElse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Something   Something              `protobuf:"varint,2,opt,name=something,enum=acme.v1.Something"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SomethingElse) Reset() {
	*x = SomethingElse{}
	mi := &file_acme_v1_acme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomethingElse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomethingElse) ProtoMessage() {}

func (x *SomethingElse) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_acme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SomethingElse) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SomethingElse) GetSomething() Something {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Something
		}
	}
	return Something_SOMETHING_UNSPECIFIED
}

func (x *SomethingElse) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SomethingElse) SetSomething(v Something) {
	x.xxx_hidden_Something = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SomethingElse) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SomethingElse) HasSomething() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SomethingElse) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *SomethingElse) ClearSomething() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Something = Something_SOMETHING_UNSPECIFIED
}

type SomethingElse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      *string
	Something *Something
}

func (b0 SomethingElse_builder) Build() *SomethingElse {
	m0 := &SomethingElse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Something != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Something = *b.Something
	}
	return m0
}

var File_acme_v1_acme_proto protoreflect.FileDescriptor

const file_acme_v1_acme_proto_rawDesc = "" +
	"\n" +
	"\x12acme/v1/acme.proto\x12\aacme.v1\"\xca\x02\n" +
	"\aExample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x18\n" +
	"\ahobbies\x18\x03 \x03(\tR\ahobbies\x12:\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1e.acme.v1.Example.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x05email\x18\x05 \x01(\tH\x00R\x05email\x12#\n" +
	"\fphone_number\x18\x06 \x01(\x05H\x00R\vphoneNumber\x127\n" +
	"\x0enested_example\x18\a \x03(\v2\x10.acme.v1.ExampleR\rnestedExample\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0eoptional_field\"U\n" +
	"\rSomethingElse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\tsomething\x18\x02 \x01(\x0e2\x12.acme.v1.SomethingR\tsomething*L\n" +
	"\tSomething\x12\x19\n" +
	"\x15SOMETHING_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSOMETHING_ONE\x10\x01\x12\x11\n" +
	"\rSOMETHING_TWO\x10\x02Bg\n" +
	"\vcom.acme.v1B\tAcmeProtoP\x01Z\x10_/acme/v1;acmev1\xa2\x02\x03AXX\xaa\x02\aAcme.V1\xca\x02\aAcme\\V1\xe2\x02\x13Acme\\V1\\GPBMetadata\xea\x02\bAcme::V1b\beditionsp\xe8\a"

var file_acme_v1_acme_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_acme_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_acme_v1_acme_proto_goTypes = []any{
	(Something)(0),        // 0: acme.v1.Something
	(*Example)(nil),       // 1: acme.v1.Example
	(*SomethingElse)(nil), // 2: acme.v1.SomethingElse
	nil,                   // 3: acme.v1.Example.MetadataEntry
}
var file_acme_v1_acme_proto_depIdxs = []int32{
	3, // 0: acme.v1.Example.metadata:type_name -> acme.v1.Example.MetadataEntry
	1, // 1: acme.v1.Example.nested_example:type_name -> acme.v1.Example
	0, // 2: acme.v1.SomethingElse.something:type_name -> acme.v1.Something
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acme_v1_acme_proto_init() }
func file_acme_v1_acme_proto_init() {
	if File_acme_v1_acme_proto != nil {
		return
	}
	file_acme_v1_acme_proto_msgTypes[0].OneofWrappers = []any{
		(*example_Email)(nil),
		(*example_PhoneNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_acme_proto_rawDesc), len(file_acme_v1_acme_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_acme_proto_goTypes,
		DependencyIndexes: file_acme_v1_acme_proto_depIdxs,
		EnumInfos:         file_acme_v1_acme_proto_enumTypes,
		MessageInfos:      file_acme_v1_acme_proto_msgTypes,
	}.Build()
	File_acme_v1_acme_proto = out.File
	file_acme_v1_acme_proto_goTypes = nil
	file_acme_v1_acme_proto_depIdxs = nil
}
