// Code generated by protoc-gen-go-protojson. DO NOT EDIT.
package acmev1 // _/acme/v1

import (
  json "encoding/json"

  protojson "google.golang.org/protobuf/encoding/protojson"
)

var (
  _ json.Marshaler   = (*Example)(nil)
  _ json.Unmarshaler = (*Example)(nil)
)

// MarshalJSON instructs encoding/json marshaler use protojson implementation.
func (m Example) MarshalJSON() ([]byte, error) {
  return protojson.Marshal(&m)
}

// UnmarshalJSON instructs encoding/json unmarshaler use protojson implementation.
func (m *Example) UnmarshalJSON(data []byte) error {
  return protojson.Unmarshal(data, m)
}

var (
  _ json.Marshaler   = (*SomethingElse)(nil)
  _ json.Unmarshaler = (*SomethingElse)(nil)
)

// MarshalJSON instructs encoding/json marshaler use protojson implementation.
func (m SomethingElse) MarshalJSON() ([]byte, error) {
  return protojson.Marshal(&m)
}

// UnmarshalJSON instructs encoding/json unmarshaler use protojson implementation.
func (m *SomethingElse) UnmarshalJSON(data []byte) error {
  return protojson.Unmarshal(data, m)
}
