// Code generated by protoc-gen-go-protojson. DO NOT EDIT.
package unversioned // _/acme/v1/unversioned

import (
  json "encoding/json"

  protojson "google.golang.org/protobuf/encoding/protojson"
)

var (
  _ json.Marshaler   = (*ExampleUnversioned)(nil)
  _ json.Unmarshaler = (*ExampleUnversioned)(nil)
)

// MarshalJSON instructs encoding/json marshaler use protojson implementation.
func (m ExampleUnversioned) MarshalJSON() ([]byte, error) {
  return protojson.Marshal(&m)
}

// UnmarshalJSON instructs encoding/json unmarshaler use protojson implementation.
func (m *ExampleUnversioned) UnmarshalJSON(data []byte) error {
  return protojson.Unmarshal(data, m)
}
