// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: acme/v1/unversioned/acme.proto

//buf:lint:ignore PACKAGE_VERSION_SUFFIX

package unversioned

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleUnversioned struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExampleUnversioned) Reset() {
	*x = ExampleUnversioned{}
	mi := &file_acme_v1_unversioned_acme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleUnversioned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleUnversioned) ProtoMessage() {}

func (x *ExampleUnversioned) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_unversioned_acme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleUnversioned) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ExampleUnversioned) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ExampleUnversioned) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExampleUnversioned) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type ExampleUnversioned_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 ExampleUnversioned_builder) Build() *ExampleUnversioned {
	m0 := &ExampleUnversioned{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

var File_acme_v1_unversioned_acme_proto protoreflect.FileDescriptor

const file_acme_v1_unversioned_acme_proto_rawDesc = "" +
	"\n" +
	"\x1eacme/v1/unversioned/acme.proto\x12\x13acme.v1.unversioned\"(\n" +
	"\x12ExampleUnversioned\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\xa9\x01\n" +
	"\x17com.acme.v1.unversionedB\tAcmeProtoP\x01Z\x15_/acme/v1/unversioned\xa2\x02\x03AVU\xaa\x02\x13Acme.V1.Unversioned\xca\x02\x13Acme\\V1\\Unversioned\xe2\x02\x1fAcme\\V1\\Unversioned\\GPBMetadata\xea\x02\x15Acme::V1::Unversionedb\beditionsp\xe8\a"

var file_acme_v1_unversioned_acme_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acme_v1_unversioned_acme_proto_goTypes = []any{
	(*ExampleUnversioned)(nil), // 0: acme.v1.unversioned.ExampleUnversioned
}
var file_acme_v1_unversioned_acme_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acme_v1_unversioned_acme_proto_init() }
func file_acme_v1_unversioned_acme_proto_init() {
	if File_acme_v1_unversioned_acme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_unversioned_acme_proto_rawDesc), len(file_acme_v1_unversioned_acme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_unversioned_acme_proto_goTypes,
		DependencyIndexes: file_acme_v1_unversioned_acme_proto_depIdxs,
		MessageInfos:      file_acme_v1_unversioned_acme_proto_msgTypes,
	}.Build()
	File_acme_v1_unversioned_acme_proto = out.File
	file_acme_v1_unversioned_acme_proto_goTypes = nil
	file_acme_v1_unversioned_acme_proto_depIdxs = nil
}
